spring:
  application:
    name: ComfyUIAPI
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      database: comfyui
      #username: admin
      #password: 123456
logging:
  config: classpath:logback/logback.xml
server:
  port: 8080
comfyui:
  baseurl: https://xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/
  client-id: xxxxxxxxxxxxxxxxxxxxxxxxxxxx
minio:
  host: http://127.0.0.1:9000
  bucket: comfyui
  access-key: xxxxxxxxxxx
  secret-key: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx