version : '3.8'
name: workserver
services:
  mongo:
    image: mongodb/mongodb-community-server:5.0.24-ubuntu2004
    container_name: mongo
    restart: on-failure:3
    ports:
      - "27017:27017"
    volumes:
      - D:\DockerData\MongoData\db:/data/db
      - D:\DockerData\MongoData\configdb:/data/configdb
  minio:
    container_name: minio
    image: quay.io/minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - "MINIO_ROOT_USER=Petted4018"
      - "MINIO_ROOT_PASSWORD=d3qEkxLC4oHU"
    command: server --console-address ":9001" /data
    volumes:
      - D:\DockerData\MinioData:/data
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 5s
      timeout: 5s
      retries: 5